### ISSUE TITLE
installing devbio-napari via conda

### ISSUE THREAD

**Issue by maryebrown1** [conda-forge/devbio-napari-feedstock#2]
### Comment:

I ran into this error message when attempting to install the devbio napari plugin via conda:
``ERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::qt-5.12.9-h556501e_6'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.12.9-h556501e_6
location of failed script: C:\Users\marye\anaconda3\envs\napari-env\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

How do I resolve this error? I'm not experienced in coding and am unsure of interpreting this error. Thank you for your help.

**Comment by haesleinhuepf** [comment]
This has been solved in this thread:
https://forum.image.sc/t/installing-devbio-plugin-in-napari/65855/27
